# Generated by Django 2.0 on 2019-10-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsdnBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='static/imgs/banner', verbose_name='用户头像')),
                ('user_name', models.CharField(max_length=255, verbose_name='博客发布人')),
                ('blog', models.CharField(max_length=255, verbose_name='博客简介')),
                ('zan', models.IntegerField(default=0, verbose_name='点赞人数')),
                ('liulan', models.IntegerField(default=0, verbose_name='浏览人数')),
                ('blog_time', models.CharField(max_length=255, verbose_name='博客发布日期')),
            ],
            options={
                'verbose_name': 'csdn博客',
                'verbose_name_plural': 'csdn博客',
                'db_table': 'csdnblog',
            },
        ),
    ]
