# Generated by Django 2.0 on 2019-10-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdnblog',
            name='blog_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='博客类别'),
        ),
        migrations.AlterField(
            model_name='csdnblog',
            name='blog',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='博客简介'),
        ),
        migrations.AlterField(
            model_name='csdnblog',
            name='blog_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='博客发布日期'),
        ),
        migrations.AlterField(
            model_name='csdnblog',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='博客发布人'),
        ),
    ]
