# Generated by Django 2.0 on 2019-10-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0003_auto_20191023_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csdnblog',
            name='blog_info',
        ),
        migrations.AddField(
            model_name='csdnblog',
            name='blog_content',
            field=models.TextField(blank=True, null=True, verbose_name='博客内容'),
        ),
        migrations.AddField(
            model_name='csdnblog',
            name='blog_intro',
            field=models.TextField(blank=True, null=True, verbose_name='博客简介'),
        ),
    ]
