# Generated by Django 2.0 on 2019-10-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0005_auto_20191023_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csdnblog',
            name='blog_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='博客发布日期'),
        ),
    ]
