# Generated by Django 2.0 on 2019-10-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0006_auto_20191023_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csdnblog',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/imgs/csdnblog', verbose_name='用户头像'),
        ),
    ]
