# Generated by Django 2.0 on 2019-10-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0008_zancsdnblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdnblog',
            name='user_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='博客标题'),
        ),
    ]
