# Generated by Django 2.0 on 2019-10-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0009_csdnblog_user_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csdnblog',
            old_name='user_title',
            new_name='blog_title',
        ),
    ]
