# Generated by Django 2.0 on 2019-10-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0011_csdnblog_blog_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='博客类型名')),
            ],
            options={
                'verbose_name': '博客分类表',
                'verbose_name_plural': '博客分类表',
                'db_table': 'blogtype',
            },
        ),
    ]
