# Generated by Django 2.0 on 2019-10-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0013_auto_20191024_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='csdnblog',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
