# Generated by Django 2.0 on 2019-10-24 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0015_csdnblog_blog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csdnblog',
            name='blog_type',
        ),
    ]
