# Generated by Django 2.0 on 2019-10-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0016_remove_csdnblog_blog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csdnblog',
            name='user_img',
        ),
    ]
