# Generated by Django 2.0 on 2019-10-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0017_remove_csdnblog_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='csdnblog',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/imgs/csdnblog', verbose_name='用户头像'),
        ),
    ]
