# Generated by Django 2.0 on 2019-10-29 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0018_csdnblog_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiuLanCsdnBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='浏览人')),
                ('liulan_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='浏览时间')),
                ('blog_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='csdn.CsdnBlog', verbose_name='博客id')),
            ],
            options={
                'verbose_name': '浏览表',
                'verbose_name_plural': '浏览表',
                'db_table': 'liulancsdnblog',
            },
        ),
    ]
