# Generated by Django 2.0 on 2019-10-29 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csdn', '0019_liulancsdnblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liulancsdnblog',
            old_name='blog_id',
            new_name='blog',
        ),
    ]
