# Generated by Django 2.0 on 2019-10-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_src', models.ImageField(blank=True, null=True, upload_to='static/imgs/banner', verbose_name='轮播图片')),
                ('banner_level', models.IntegerField(default=0, verbose_name='图片优先级')),
                ('banner_url', models.CharField(max_length=255, verbose_name='轮播详情')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'banner',
            },
        ),
    ]
